### ISSUE TITLE
Will the use of `{all: true}` make the API less future proof?

### ISSUE THREAD

**Issue by jespertheend** [privacycg/saa-non-cookie-storage#1]
Right now this extension is backwards compatible with previous `requestStorageAccess()` calls because older browsers don't expect any parameters. But if an `all` options is added, this can really only be done once.

Say an initial implementation ships with support for `{localStorage: true, indexedDB: true}`, with `{all: true}` as shorthand.
Then future implementations would not be able to add `sharedWorker: true` and also make it fall under `all: true` without the risk of breaking existing websites.

**Comment by arichiv** [comment]
There isn't a formal spec yet, but ideally the design would call for (1) no exceptions thrown if the 'all' requests a type not available in the given context (so forward compatibility is maintained) and (2) no exception thrown if an unsupported type is requested (so backward compatibility is maintained).

**Comment by jespertheend** [comment]
Ah, sorry. I only realised just now that `requestStorageAccess()` will return a handle.
For a second I thought it would affect existing api calls as well.
