### ISSUE TITLE
Understanding the API

### ISSUE THREAD

**Issue by Alm0g** [privacycg/saa-non-cookie-storage#10]
Hey!
We have a Chrome extension that embeds an iframe in sites upon the user clicking the extension icon, or automatically embeds that iframe if configured to do so.
[Example-1](https://github.com/arichiv/saa-non-cookie-storage?tab=readme-ov-file#example-1) perfectly describes our problem after partitioning the storage & communication APIs.
 
I came across this solution, registered to the Origin Trial with my localhost domain, set the [Storage Access API](chrome://flags/#storage-access-api) flag to `enable (with prompt)`, and well, it just seems to work... But I don't understand why.
I embedded a localhost-hosted iframe in tab A (tabA/localhost) and tab B (tabB/localhost).
In tab A, I clicked a button that invokes the following code which writes to `handle.localStorage`:
```
let handle = await document.requestStorageAccess({
  localStorage: true,
});
handle.localStorage.setItem("userid", "1234");
```
I expected a popup prompting the user to allow sharing data across contexts, but it didn't appear.
Then, in tab B, I read `handle.localStorage`:
```
let handle = await document.requestStorageAccess({
  localStorage: true,
});
console.log({ ...handle.localStorage });
```
`userid: 1234` appeared, so it works just like `window.localStorage`.

My confusion results from the fact that no prompt window appeared. Is this intended? Am I missing something?

Thanks a lot!
With much appreciation :)

**Comment by arichiv** [comment]
If third-party cookies aren't blocked then the prompt is bypassed.
![image](https://github.com/arichiv/saa-non-cookie-storage/assets/666538/b78af228-843c-42da-90ef-12b5ccd81c57)

**Comment by Alm0g** [comment]
Oh, that makes sense. Thanks!
