### ISSUE TITLE
localStorage handle within iframe is different from localStorage contents of page loaded top-level

### ISSUE THREAD

**Issue by antimatter15** [privacycg/saa-non-cookie-storage#11]
For example, let's say I have a site A that embeds site B, and a site C that also embeds site B. Site B has some code which stores/shows data in localStorage. Without using requestStorageAccess, due to storage partitioning, viewing site B directly, viewing site A, and viewing site C will all have different buckets. When using requestStorageAccess with cookies, accessing `document.cookie` in site B directly, when it is embedded in site A, and embedded in site C, they will all load the same contents, as expected. When using `requestStorageAccess({all: true})` where site B is enlisted in the origin trial, it seems that the localStorage of the returned handle when embedded in both site A and site C show the same contents, but that those contents are different from the localStorage accessible from viewing site B directly. 

For example, in https://caddr-origin.github.io/examples/basic-storage-v2/ I have a page which loads https://4ki77nvzueuneq2b53uo27uzr3ud5v4tmmmmm6yufiozfurfdsa.caddr.org/?src=https://caddr-origin.github.io/examples/basic-storage-v2/contract.js in an iframe, where *.caddr.org is enlisted in the origin trial.

**Comment by arichiv** [comment]
I built a demo and it works for me.

Open https://granite-juicy-restaurant.glitch.me/ in a new tab and click in the window:
![image](https://github.com/arichiv/saa-non-cookie-storage/assets/666538/ac4d7261-9486-4ea1-9e26-96d4e9f158b4)

Now open https://vaulted-agreeable-payment.glitch.me/ in a new tab and click the button:
![image](https://github.com/arichiv/saa-non-cookie-storage/assets/666538/d670fd9f-4139-45c4-a88f-48f7f30234f5)

After you click allow, it should display a random number:
![image](https://github.com/arichiv/saa-non-cookie-storage/assets/666538/cbee693a-7344-41ff-8b97-94beefb2acfd)

If you refresh the other tab it should have the same number now:
![image](https://github.com/arichiv/saa-non-cookie-storage/assets/666538/6706b55e-78b0-4ff3-a4ee-2c95bb5033c1)
 
You can see the source here:
https://glitch.com/edit/#!/granite-juicy-restaurant
https://glitch.com/edit/#!/vaulted-agreeable-payment

**Comment by antimatter15** [comment]
It seems that if you open https://vaulted-agreeable-payment.glitch.me/ first and click the button to set the unpartitioned local storage and then subsequently open https://granite-juicy-restaurant.glitch.me/ it still says "Found: null". Is this expected behavior?

**Comment by arichiv** [comment]
It's not! This does seem to be a bug, I'll look into a fix tomorrow. It seems the handle's localStorage ends up just being the partitioned one for some reason:
![image](https://github.com/arichiv/saa-non-cookie-storage/assets/666538/a2a8311a-8c86-4ae8-80cb-bf66202ce5f2)

**Comment by arichiv** [comment]
Fix is up for review to be included in M122: https://chromium-review.googlesource.com/c/chromium/src/+/5177156

**Comment by arichiv** [comment]
The fix is in, but I'll leave this issue open so any others experiencing the issue know what's up. Thanks for reporting @antimatter15

**Comment by KenzoDeRidder** [comment]
Could it be that this is now broken again?
I've got a site A that's being used in both a normal tab and in an iframe. LocalStorage of the iframe one has different contents (it's empty) than that of the tabbed one.
