### ISSUE TITLE
 Cross-Domain Local Storage Issue

### ISSUE THREAD

**Issue by CodeKarRohan** [privacycg/saa-non-cookie-storage#14]
We're currently facing a challenge with our local storage setup, where it's being shared across multiple domains. With Google Chrome's recent introduction of third-party access restrictions to cookies and storage, we've encountered issues where the local storage is being partitioned, preventing our third-party domains from accessing the stored data.

Upon investigation, we've come across a potential solution involving the Storage Access API (specifically, requestStorageAccess) and related website settings. However, we're uncertain if this is the recommended approach for our use case. We're seeking guidance on whether this method is advisable or if there are more efficient alternatives available.

Additionally, we have a scenario where our associated **domain names are dynamic,** making it impractical to add them to the related website set. Despite this, we'd like to maintain the use of local storage for data sharing between domains.

We're reaching out to you for assistance in exploring potential solutions to address these challenges. Any insights or recommendations you can provide would be greatly appreciated.

Thank you for your attention to this matter.

**Comment by arichiv** [comment]
requestStorageAccess probably is the best way to adapt given the constraints you described. Have you tried building out a test of the API? There are a few tricky requirements (if A embeds B and B calls requestStorageAccess then (1) the request must be in response to a user interaction with AB's iframe and (2) the user must have interacted with B as a top-level site at some point in the past).

**Comment by johannhof** [comment]
I would also be interested in more details about your "dynamic" domain names regarding RWS, but that may be better explained in a separate issue on https://github.com/WICG/first-party-sets. :)

**Comment by johannhof** [comment]
I would also be interested in more details about your "dynamic" domain names regarding RWS, but that may be better explained in a separate issue on https://github.com/WICG/first-party-sets. :)
