### ISSUE TITLE
Requesting storage access for shared workers.

### ISSUE THREAD

**Issue by jespertheend** [privacycg/saa-non-cookie-storage#2]
How would requesting storage access for SharedWorkers work?
Specifically, what should happen to existing workers when `requestStorageAccess({sharedWorker: true})` is called?

While SharedWorkers are partitioned, it's possible for the same SharedWorker url to exist multiple times. Merging existing workers doesn't really seem feasible, so I think the best approach would be to just leave them running until all references are lost?

**Comment by arichiv** [comment]
It would probably look something like:
```
const handle = await requestStorageAccess({sharedWorker: true});
const myWorker = new handle.SharedWorker("worker.js");
```

The pre-existing third-party context could still be used as before via:
```
const myWorker = new SharedWorker("worker.js");
```
