### ISSUE TITLE
BroadcastChannel without test-third-party-cookie-phaseout

### ISSUE THREAD

**Issue by antimatter15** [privacycg/saa-non-cookie-storage#27]
Seems like right now the new `requestStorageAccess` works for `localStorage` without the  `test-third-party-cookie-phaseout` flag, but not for `BroadcastChannel` — it returns an object which includes the `BroadcastChannel` except it never seems to fire. 

It would be nice if the `BroadcastChannel` functionality worked as well, or at least if there were a good way to test for support.

**Comment by arichiv** [comment]
It's working for me: https://saa-beyond-cookies.glitch.me/

**Comment by arichiv** [comment]
Ah, you're saying it's broken unless the flag is on? If so, the easiest thing to test is probably whether hasStorageAccess returns false or true before calling requestStorageAccess.
