### ISSUE TITLE
Missing BroadcastChannel in Beta 121

### ISSUE THREAD

**Issue by jcubic** [privacycg/saa-non-cookie-storage#6]
@miketaylr thanks, I just added an issue. But I have a problem with the API:

```javascript
if (is_proxy_iframe() && document.requestStorageAccess) {
    document.requestStorageAccess({
        all: true
    }).then(function(handle) {
        sa_handle = handle;
        init_channel();
    });
}

function init_channel() {
    if (sa_handle) {
        channel = new sa_handle.BroadcastChannel(uniq_prefix);
    } else {
        channel = new window.BroadcastChannel(uniq_prefix);
    }
}
```

Got an error:

> TypeError: sa_handle.BroadcastChannel is not a constructor

BroadcastChannel is missing:

![Przechwycenie obrazu ekranu_2023-12-11_14-12-51](https://github.com/privacycg/storage-access/assets/280241/f3893a73-df73-4652-ad38-a47d4ee48046)

It seems that `sa_handle.BroadcastChannel` is available but from the Prototype.

So I use this code:

```javascript
if (sa_handle) {
  if (sa_handle.hasOwnProperty('BroadcastChannel')) {
    channel = new sa_handle.BroadcastChannel(uniq_prefix);
  }
} else {
  channel = new window.BroadcastChannel(uniq_prefix);
}
if (!channel) {
  return;
}
```

Fallback to localStorage works.

```

I'm using 121.0.6167.8 Beta.

**Comment by arichiv** [comment]
It's not:
`channel = new sa_handle.BroadcastChannel(uniq_prefix);`
it's:
`channel = sa_handle.BroadcastChannel(uniq_prefix);`

**Comment by jcubic** [comment]
How come, if it always was a constructor: See [MDN](https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel/BroadcastChannel).

**Comment by arichiv** [comment]
We can reconsider the interface, it was implemented that way because having code like `new localObject.ClassName` seemed like more of an anti-pattern than `localObject.MemberFunction`. I'm open to changing it

**Comment by gerneio** [comment]
If going the MemberFunction route, probably just needs a better name for better context (i.e. `getBroadcastChannel` or something similiar).
