### ISSUE TITLE
Missing permission prompt

### ISSUE THREAD

**Issue by jcubic** [privacycg/saa-non-cookie-storage#7]
The code just works without any interaction from the user. It is supposed to prompt the user and ask for permission but it doesn't do that.

this is part of the documentation:

```javascript
// Request a new storage handle via rSA (this should prompt the user)
const handle = await document.requestStorageAccess({all: true});
```

This is my code:

```javascript
document.requestStorageAccess({
    all: true
}).then(function(handle) {
    sa_handle = handle;
});
```

Tested in Chrome 121.0.6167.8 Beta

**Comment by arichiv** [comment]
If the permission has already been granted it persists for 30 days for a given inner-iframe-origin/top-site combo.

**Comment by jcubic** [comment]
I never granted the permission. This is the first time I use this API.

**Comment by arichiv** [comment]
Can you describe the composition of frames, their origins, and which frame makes that call?

**Comment by jcubic** [comment]
Here are the links to my demos:

https://just.net.pl/sysend.php?_=local

https://jcubic.pl/sysend.php?_=local

They both have the iframes of the opposite domains. They both send postMessage and send a cross-origin event with localStorage storage event because BroadcastChanel didn't work with `new`.

**Comment by arichiv** [comment]
I'm having trouble figuring out what's happening, can you describe the composition of frames, their origins, and which frame makes what calls and sends what messages or writes what storage?

All I do see is errors in console like:
![image](https://github.com/arichiv/saa-non-cookie-storage/assets/666538/8b0d3cdf-5f6b-4fcb-8fcc-a4289e290f9a)

**Comment by jcubic** [comment]
And you run this in Google Chrome? This is the console I have in Chrome Beta:

![Przechwycenie obrazu ekranu_2023-12-11_19-04-01](https://github.com/arichiv/saa-non-cookie-storage/assets/280241/61e1f83a-e3f2-456b-a987-99e8fb80334a)

But give me a moment I think that mistakenly tested my library on the same domain. It works only one way. I'm not sure why. Let me fix this and get back to you. I have a long explanation will post it when I fix the library for Cross-Domain communication both ways.

**Comment by jcubic** [comment]
Ok my demo is working now, I've used wrong tokens. I though that they were the same since they started the same.

So the setup is like this:

just.net.pl have iframe for jcubic.pl and terminal.jcubic.pl (my original code was on subdomains that's why it was working). 

This input:

![Przechwycenie obrazu ekranu_2023-12-11_19-05-53](https://github.com/arichiv/saa-non-cookie-storage/assets/280241/5990fa29-75f6-4e63-b73f-737835504b30)

Sends a normal message. It first uses normal BroadcastChannel to send to the same origin and then uses postMessage to send to all iframes. You only care about one for jcubic.pl. On each domain, there is sysend-proxy.php file that forwards the message to the origin it belongs to. So if the iframe is on jcubic.pl it sends to https://jcubic.pl origin. Which should show if you open that other line in a different tab.

And the same happen the other way around. ON jcubic.pl there is an iframe with terminal.jcubic.pl and just.net.pl and there is exact same process.

I was testing in both 120 and 121 and it works for both versions and don't ask for any permission.
![Peek 2023-12-11 20-24](https://github.com/arichiv/saa-non-cookie-storage/assets/280241/23e62169-1794-4066-a47a-24a8bb60a820)

I needed to disable the warnings because got a race condition in my initialization code and the library was not working 100% of the time. This is version Beta 121. The code doesn't work properly in Chrome 120.0.6099.71 even though I use localStorage, since BroadcastChannel doesn't work with a `new` keyword.

**Comment by arichiv** [comment]
So it's working as expected? And there isn't a prompt because it's all subdomains of the same eTLD+1?

Which frame is calling requestStorageAccess? Are they doing so due to user interaction with that frame? https://developer.mozilla.org/en-US/docs/Web/API/Document/requestStorageAccess#return_value

**Comment by jcubic** [comment]
Both domains call requestStorageAccess inside an iframe. It's called to get the channel (that is not working) or localStorage instance. It's required to send the message cross-domain.

But I think that I've tested and recorded the wrong domains again. I'm not able to make the Cross-Domain communication work. I've added proper tokens and it's not working.

It only works by sending a message from just.net.pl tab => jcubic.pl iframe => jcubic.pl tab.
Are you sure that the API is working correctly?

I've added a bunch of console.logs to the code but I've removed them because I thought they caused a race condition when Dev Tools was open. Tomorrow I will try to look closer into my code and see where the message is not sent.

And a Note: I do send a message from just.net.pl to jcubic.pl without asking permission. So the original issue I'm having is still there.

**Comment by jcubic** [comment]
I'm not sure what is happening it works in like 10% of the cases (when I refresh the pages multiple times) and 90% of the time it only works one way.

**Comment by arichiv** [comment]
I'd guess it has to do with the frame calling requestStorageAccess not having focus: "requests are automatically denied unless the embedded content is currently processing a user gesture such as a tap or click ([transient activation](https://developer.mozilla.org/en-US/docs/Glossary/Transient_activation)), or unless permission was already granted previously"

Are you sure the handle is actually being used and some fallback isn't being triggered? It's hard to know what's happening without the code to walkthrough.

**Comment by arichiv** [comment]
Okay I built a demo that works (prompts the user and gets the handle in return via the OT):
Demo: https://hexagonal-gleaming-expansion.glitch.me/
Outer frame source: https://glitch.com/edit/#!/hexagonal-gleaming-expansion
Inner frame source: https://glitch.com/edit/#!/granite-juicy-restaurant

**Comment by jcubic** [comment]
In Beta, I didn't have any permission prompt. All I have is success showing immediately. The same happens in Stable 120. Maybe I need to configure something.

**Comment by jcubic** [comment]
So I've fixed my library, now everything is working and events are sent across domains.

But still not sure what I should do with the permission prompt. I have only this option enabled `Third-party Storage Partitioning` in `about://flags`. Do I need to add some more options?

**Comment by arichiv** [comment]
Does my demo not yield a permission prompt? Because I'm definitely seeing it 100% of the time unless I have already granted it. Could you screenshot the permissions list for the demo site after you click the button? (note: I updated the demo links above so the code is all in glitch.me now)

![image](https://github.com/arichiv/saa-non-cookie-storage/assets/666538/5b0f2530-db15-484d-8840-a977fc2af898)

**Comment by jcubic** [comment]
![Przechwycenie obrazu ekranu_2023-12-12_17-50-09](https://github.com/arichiv/saa-non-cookie-storage/assets/280241/3e5b87e8-8aa2-4383-b305-8b245200b84e)

Note that I'm using Chrome on Linux if that makes a difference.

**Comment by arichiv** [comment]
Something weird is going on yeah, can you try this with no special flags set? I wonder if storage partitioning is off or something somehow.

Edit: try with the 'block all third-party cookies' setting on

**Comment by jcubic** [comment]
Setting 'block all third-party cookies' in settings makes the permission prompt visible.

Will check my code to see how it works. Note that probably should be added to the Origin Trail website that this option needs to be enabled to have the permission prompt.

**Comment by jcubic** [comment]
Just checked my app, and I see the permission errors same as in your screenshot.
