### ISSUE TITLE
detect if document.requestStorageAccess accept argument

### ISSUE THREAD

**Issue by jcubic** [privacycg/saa-non-cookie-storage#8]
I was testing the API in Firefox and it gives errors when calling outside of the user event.

There is no information about this at [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/requestStorageAccess), but I suspect that this is only by accident. But MDN says that the result value should be undefined, and this is what I was having without the Origin Trial.

Is there a way to detect this new API somehow, without testing a user agent?

**Comment by arichiv** [comment]
What error are you getting in Firefox? It seems to ignore the extra arguments and just return undefined. Detecting the undefined vs handle being returned is probably the easiest way. If (success && handle) OT_SAA_CODE_PATH else if (success && undefined) SAA_CODE_PATH else NO_SAA_CODE_PATH

**Comment by jcubic** [comment]
Yes, but the code gives an error in the console that is not an exception so you can't catch it.

The error in Firefox says:

> document.requestStorageAccess() may only be requested from inside a short running user-generated event handler.

with a link to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/requestStorageAccess). It's hard to run the code inside an event handler if it's inside the iframe. It would be nice to detect this new API before calling that function.

**Comment by arichiv** [comment]
Interesting, yeah I'm not aware of a way to detect it without calling given there's two versions defined and one takes 0 arguments

**Comment by jcubic** [comment]
That would work if `document.requestStorageAccess.length` would return 1 but it returns 0 in Chrome. Maybe because the options are optional. But if they are required then it would be nice if length return 1.

**Comment by arichiv** [comment]
They're not required, there are two versions of the function at the moment and we cannot break API compatibility.

**Comment by arichiv** [comment]
If this [additional extension](https://arichiv.github.io/saa-non-cookie-storage/omit-unpartitioned-cookies.html) goes in M123 you could detect the existence of `hasUnpartitionedCookieAccess` to know if the SAA extensions are active.

**Comment by jcubic** [comment]
Awesome, it's great news.

**Comment by jcubic** [comment]
@arichiv is there a way to propose change of the name? This is silly to put cookie if you can in future request broadcasChannel only permission.

Why not `hasUnpartitionedAccess` for me `PartitionAccess` is a clearn name.

Also why the name is a negative (you will get double negatives if you want see if the cookie is partitioned)? Why not `hasPartitionedAccess`?

I can rise another issue if you want.

**Comment by arichiv** [comment]
`hasUnpartitionedCookieAccess` (like `hasStorageAccess`) returns true if and only if unpartitioned cookies were made available. They are not directly checking if `storage-access` permission was granted via a call to `requestStorageAccess`).

If you want to check the state of the permission you can use `navigator.permissions.query(...)`.

The reason for a cookie specific API is that access can be granted to unpartitioned cookies without asking for the handle at all. All other storage mediums require the handle to use, and you can just check the handle to know if you have access to them.

If you call `requestStorageAccess({BroadcastChannel: true})` then `hasUnpartitionedCookieAccess` (like `hasStorageAccess`) would both return false after this change. Currently, cookie access is compulsory so both would return true as though the types dictionary always had `cookies: true` in it.

**Comment by arichiv** [comment]
As for why not `hasPartitionedCookieAccess`, that's a different function entirely and not just the inverse function. You don't lose access to partitioned cookies when you gain access to unpartitioned cookies.

**Comment by jcubic** [comment]
I want to check if it's safe to call the function with an object or if it's a browser that doesn't support this feature. So I need to check double negative !hasUnpartitionedCookieAccess to see if Storage Partition is implemented or not and I don't care about cookies at all I want to access broadcastChannel. The code will look silly if you read it.

Or should I just check if hasUnpartitionedCookieAccess exists?

**Comment by arichiv** [comment]
I'm saying you could just check if it exists as it's a new function in this origin trial. Hopefully it will be in M123.
